line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203"]  # match black on slices

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[lint.flake8-bugbear]
extend-immutable-calls = ["Depends", "fastapi.Depends"]